config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  
  resources :contacts, only: [:index, :create]
  resources :warranty, only: [:index, :create]
  resources :users, only: [:index, :edit, :update, :destroy, :show]
  resources :pools
  resources :waters

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#index'
  
  get 'startup_faq', to: 'static#startup_faq', as: 'startup_faq'
  get 'documents', to: 'static#documents', as: 'documents'
  get 'interactive_help', to: 'static#interactive_help', as: 'interactive_help'
  # get 'tutorial/:tutorial', to: 'static#tutorial', as: 'tutorial'
  get 'pool_tutorial', to: 'static#pool_tutorial', as: 'pool_tutorial'
  get 'spa_tutorial', to: 'static#spa_tutorial', as: 'spa_tutorial'
  get 'commercial_tutorial', to: 'static#commercial_tutorial', as: 'commercial_tutorial'
  get 'basics_partials', to: 'static#basics_partials', as: 'basics_partials'
  get 'ecosmarte_university', to: 'static#ecosmarte_university', as: 'ecosmarte_university'
  get 'ecosmarte_basics', to: 'static#ecosmarte_basics', as: 'ecosmarte_basics'
  get 'quiz/:quiz_number', to: 'static#quiz', as: 'quiz'
  post 'quiz_answer', to: 'static#quiz_answer', as: 'quiz_answer'
  get 'videos', to: 'static#videos', as: 'videos'
  
  get 'password_edit/:id', to: 'users#password_edit', as: 'password_edit'
  patch 'password_update/:id', to: 'users#password_update', as: 'password_update'
  
  get 'user_profile', to: 'users#user_profile', as: 'user_profile'
  get 'user_profile_edit', to: 'users#user_profile_edit', as: 'user_profile_edit'
  patch 'user_profile_update', to: 'users#user_profile_update', as: 'user_profile_update'
  get 'user_password_edit', to: 'users#user_password_edit', as: 'user_password_edit'
  patch 'user_password_update', to: 'users#user_password_update', as: 'user_password_update'
  
  get 'user_pools', to: 'pools#user_pools', as: 'user_pools'
  get 'add_pool', to: 'pools#add_pool', as: 'add_pool'
  get 'admin_edit_pool/:pool_id', to: 'pools#admin_edit_pool', as: 'admin_edit_pool'
  
  get 'new_water_measurement/:pool_id', to: 'waters#new_water_measurement', as: 'new_water_measurement'
  get 'user_water_measurements', to: 'waters#user_water_measurements', as: 'user_water_measurements'
  get 'pool_water_measurements/:pool_id', to: 'waters#pool_water_measurements', as: 'pool_water_measurements'
  
  get 'international', to: 'static#international', as: 'international'
  post 'international_mail', to: 'static#international_mail', as: 'international_mail'
  get 'ecosmarte__wifi', to: 'static#ecosmarte_wifi', as: 'ecosmarte_wifi'
  get 'privacy_policy', to: 'static#privacy_policy', as: 'privacy_policy'
  
end

app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :user
  belongs_to :pool_model, optional: true
  has_many :waters
  
  enum filter_type: %w(sand glass de cartridge)
  enum pump_size: %w(1/2_horse_power 3/4_horse_power 1_horse_power 1_1/2_horse_power 2_horse_power variable_speed)
  enum volume_unit: %w(gallons litters)
  enum filter_size_unit: %w(lbs kg)
  enum state: %w(alabama alaska arizona arkansas california colorado connecticut delaware florida georgia 
  hawaii idaho illinois indiana iowa kansas kentucky louisiana maine maryland massachusetts michigan minnesota 
  mississippi missouri montana nebraska nevada new_hampshire new_jersey new_mexico new_york north_carolina
  north_dakota ohio oklahoma oregon pennsylvania rhode_island south_carolina south_dakota tennessee texas utah
  vermont virginia washington west_virginia wisconsin wyoming)
  
  def self.get_user_pools(user_id)
    Pool.where(user_id: user_id)
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  include StrongParamsHolder
  
  before_action :authenticate_user!

  def index
    @pools = Pool.all
  end

  def show
    @pool = Pool.find(params[:id])
  end

  def new
    @pool = Pool.new()
  end

  def create
    @pool = Pool.new(pool_params)
    if @pool.save
      if current_user.user_type == "admin"
        redirect_to pools_path
      else 
        redirect_to user_pools_path
      end
    else
      render :new
    end
  end

  def edit
    @pool = Pool.find(params[:id])
  end

  def update
    @pool = Pool.find(params[:id])
    if @pool.update_attributes(pool_params)
      if current_user.user_type == "admin"
        redirect_to pools_path
      else 
        redirect_to user_pools_path
      end
    else
      render :edit
    end
  end

  def destroy
    @pool = Pool.find(params[:id])
    @pool.destroy
    if current_user.user_type == "admin"
      redirect_to pools_path
    else 
      redirect_to user_pools_path
    end
  end
  
  def user_pools
    @pools = Pool.get_user_pools(current_user.id)
    render :index
  end
  
  def add_pool
    @pool = Pool.new
    render :new_pool
  end
  
  def admin_edit_pool
    @pool = Pool.find(params[:pool_id])
    render :new_pool
  end
end

app/helpers/pools_helper.rb
module PoolsHelper
  
  def pool_model_array
    pool_model_array =  PoolModel.all.map { |model| [model.description, model.id] }
  end
  
  def user_array
    user_array =  User.all.map { |user| [user.name, user.id] }
  end
  
end

app/views/pools/_form.html.erb
<!-- Logo -->
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <%= image_tag 'ecosmarte.png', class: 'logo_eco' %>
  </div>
</div>
<!--  ------>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for @pool, html: {class: 'form-horizontal'}, novalidate: 'novalidate' do |f| %>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :pool_name, class: "col-sm-3 control-label" %>
          <div class="col-sm-8">
            <%= f.text_field :name, class: "form-control", required: "required", autofocus: true %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :product_model, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.select :pool_model_id, pool_model_array, {include_blank: "Choose a model"}, {class: "form-control"} %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :pool_volume, class: "col-sm-3 control-label"%>
          <div class="col-sm-5">
            <%= f.text_field :volume, class: "form-control", autofocus: true  %>
          </div>
          <div class="col-sm-3">
            <%= f.select :volume_unit, options_for_select(Pool.volume_units.keys.map { |t| [t.humanize, t] }, @pool.volume_unit), {include_blank: "Choose unit"}, {class: "form-control"} %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :pump_size, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.select :pump_size, options_for_select(Pool.pump_sizes.keys.map { |t| [t.humanize.titleize, t] }, @pool.pump_size), {include_blank: "Choose"}, {class: "form-control"} %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :filter_type, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.select :filter_type, options_for_select(Pool.filter_types.keys.map { |t| [t.humanize.titleize, t] }, @pool.filter_type), {include_blank: "Choose"}, {class: "form-control"} %>
          </div>
        </div>
      </div>
      
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :filter_size, class: "col-sm-3 control-label"%>
          <div class="col-sm-5">
            <%= f.text_field :filter_size, class: "form-control", autofocus: true  %>
          </div>
          <div class="col-sm-3">
            <%= f.select :filter_size_unit, options_for_select(Pool.filter_size_units.keys.map { |t| [t, t] }, @pool.filter_size_unit), {include_blank: "Choose unit"}, {class: "form-control"} %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :vacuum_brand, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :vacuum_brand, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :attached_spa, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.select :attached_spa, options_for_select([['No', true], ['Yes', false]], selected: @pool.attached_spa),{include_blank: "Choose"}, {class: "form-control"} %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :negative_edge, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.select :negative_edge, options_for_select([['No', true], ['Yes', false]], selected: @pool.negative_edge),{include_blank: "Choose"}, {class: "form-control"} %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :additional_water_features, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :additional_water_features, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :address, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :address, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :city, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :city, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :postal_code, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :postal_code, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :state, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.select :state, options_for_select(Pool.states.keys.map { |t| [t.humanize.titleize, t] }, @pool.state), {include_blank: "Choose a state"}, {class: "form-control"} %>
            <%#= f.text_field :state, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <%= f.hidden_field :user_id, value: current_user.id %>
      
      <div class="row">
        <div class="actions">
          <%= f.submit "Save", class: "btn btn-tutorial" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/pools/index.html.erb
<h1>Pools</h1>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="table-responsive">
        <table class="table">
          <tr>
            <th>Pool Name</th>
            <th>Costumer Name</th>
            <th>Model</th>
            <th>Actions</th>
          </tr>
          <% @pools.each do |pool| %>
            <tr>
              <td><%= pool.name %></td>
              <td><%= pool.user.name %></td>
              <td><%= pool.pool_model.description if pool.pool_model.present? %></td>

              <td>
                <%= link_to pool_path(pool), class:"btn btn-success btn-circle" do %>
                  <i class="fa fa-eye"></i>
                <% end %>
                <% if current_user.user_type == "admin" %>
                  <%= link_to admin_edit_pool_path(pool_id: pool.id), class:"btn btn-primary btn-circle" do %>
                    <i class="fa fa-pencil"></i>
                  <% end %>
                <% else %>
                  <%= link_to edit_pool_path(pool), class:"btn btn-primary btn-circle" do %>
                    <i class="fa fa-pencil"></i>
                  <% end %>
                <% end %>
                <%= link_to pool_path(pool), class:"btn btn-danger btn-circle", method:"delete" do %>
                 <i class="fa fa-trash-o"></i>
                <% end %>
              </td>

            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>

<% if current_user.user_type == "admin" %>
<div class="">
  <%= link_to add_pool_path do %>
    <button class="btn btn-tutorial" name="button">Add New Pool</button>
  <% end %>
</div>
<% else %>
<div class="">
  <%= link_to new_pool_path do %>
    <button class="btn btn-tutorial" name="button">Add New Pool</button>
  <% end %>
</div>
<% end %>

app/views/pools/new_pool.html.erb
<div class="container-fluid">
<!-- Logo -->
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <%= image_tag 'ecosmarte.png', class: 'logo_eco' %>
  </div>
</div>
<!--  ------>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for @pool, html: {class: 'form-horizontal'}, novalidate: 'novalidate' do |f| %>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :user_name, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.select :user_id, options_for_select(user_array, @pool.user_id), {include_blank: "Choose"}, {class: "form-control", required: "required"} %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :pool_name, class: "col-sm-3 control-label" %>
          <div class="col-sm-8">
            <%= f.text_field :name, class: "form-control", autofocus: true, required: "required" %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :product_model, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.select :pool_model_id, pool_model_array, {include_blank: "Choose a model"}, {class: "form-control"} %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :pool_volume, class: "col-sm-3 control-label"%>
          <div class="col-sm-5">
            <%= f.text_field :volume, class: "form-control", autofocus: true  %>
          </div>
          <div class="col-sm-3">
            <%= f.select :volume_unit, options_for_select(Pool.volume_units.keys.map { |t| [t.humanize, t] }, @pool.volume_unit), {include_blank: "Choose unit"}, {class: "form-control"} %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :pump_size, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.select :pump_size, options_for_select(Pool.pump_sizes.keys.map { |t| [t.humanize.titleize, t] }, @pool.pump_size), {include_blank: "Choose"}, {class: "form-control"} %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :filter_type, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.select :filter_type, options_for_select(Pool.filter_types.keys.map { |t| [t.humanize.titleize, t] }, @pool.filter_type), {include_blank: "Choose"}, {class: "form-control"} %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="form-group group">
          <%= f.label :filter_size, class: "col-sm-3 control-label"%>
          <div class="col-sm-5">
            <%= f.text_field :filter_size, class: "form-control", autofocus: true  %>
          </div>
          <div class="col-sm-3">
            <%= f.select :filter_size_unit, options_for_select(Pool.filter_size_units.keys.map { |t| [t, t] }, @pool.filter_size_unit), {include_blank: "Choose unit"}, {class: "form-control"} %>
          </div>
        </div>
      </div>
        
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :vacuum_brand, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :vacuum_brand, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :attached_spa, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.select :attached_spa, options_for_select([['No', true], ['Yes', false]], selected: @pool.attached_spa),{include_blank: "Choose"}, {class: "form-control"} %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :negative_edge, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.select :negative_edge, options_for_select([['No', true], ['Yes', false]], selected: @pool.negative_edge),{include_blank: "Choose"}, {class: "form-control"} %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :additional_water_features, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :additional_water_features, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :address, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :address, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :city, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :city, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :postal_code, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :postal_code, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :state, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.select :state, options_for_select(Pool.states.keys.map { |t| [t.humanize.titleize, t] }, @pool.state), {include_blank: "Choose a state"}, {class: "form-control"} %>
            <%#= f.text_field :state, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="actions">
          <%= f.submit "Save", class: "btn btn-tutorial" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

</div>

app/views/pools/show.html.erb
<section class="container-fluid">
  <h1><%= @pool.name %></h1>

  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <div class="table-responsive">
        <table class="table">
          <tbody>
            <tr>
              <th>Pool Name</th>
              <th>Costumer Name</th>
              <th>Model</th>
              <th>Pool Volume</th>
              <th>Pump Size</th>
              <th>Filter Type</th>
              <th>Filter Size</th>
              <th>Vacuum Brand</th>
              <th>Attached Spa</th>
              <th>Negative Edge</th>
              <th>Additional Water Features</th>
            </tr>
            <tr>
              <td><%= @pool.name %></td>
              <td><%= @pool.user.name %></td>
              <td><%= @pool.pool_model.description if @pool.pool_model.present? %></td>
              <td><%= @pool.volume %> <%= @pool.volume_unit.titleize if @pool.volume_unit.present? %></td>
              <td><%= @pool.pump_size.humanize.titleize if @pool.pump_size.present? %></td>
              <td><%= @pool.filter_type.titleize if @pool.filter_type.present? %></td>
              <td><%= "#{@pool.filter_size}  #{@pool.filter_size_unit}" %></td>
              <td><%= @pool.vacuum_brand %></td>
              <td><%= yes_no(@pool.attached_spa) if @pool.attached_spa.present? %></td>
              <td><%= yes_no(@pool.negative_edge) if @pool.negative_edge.present? %></td>
              <td><%= @pool.additional_water_features %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  
  
  <h4> Pool Address</h4>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="table-responsive">
        <table class="table">
          <tbody>
            <tr>
              <th>Address</th>
              <th>City</th>
              <th>State</th>
              <th>Postal Code</th>
            </tr>
            <tr>
              <td><%= @pool.address %></td>
              <td><%= @pool.city %></td>
              <td><%= @pool.state.humanize.titleize if @pool.state.present? %></td>
              <td><%= @pool.postal_code %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <% if current_user.user_type == "admin" %>
    <%= link_to '<button class="btn btn-default" name="button">Edit</button>'.html_safe, admin_edit_pool_path(@pool.id) %>
  <% else %>
    <%= link_to '<button class="btn btn-default" name="button">Edit</button>'.html_safe, edit_pool_path(@pool.id) %>
  <% end %>


</section>