config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  
  resources :contacts, only: [:index, :create]
  resources :warranty, only: [:index, :create]
  resources :users, only: [:index, :edit, :update, :destroy, :show]
  resources :pools
  resources :waters

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#index'
  
  get 'startup_faq', to: 'static#startup_faq', as: 'startup_faq'
  get 'documents', to: 'static#documents', as: 'documents'
  get 'interactive_help', to: 'static#interactive_help', as: 'interactive_help'
  # get 'tutorial/:tutorial', to: 'static#tutorial', as: 'tutorial'
  get 'pool_tutorial', to: 'static#pool_tutorial', as: 'pool_tutorial'
  get 'spa_tutorial', to: 'static#spa_tutorial', as: 'spa_tutorial'
  get 'commercial_tutorial', to: 'static#commercial_tutorial', as: 'commercial_tutorial'
  get 'basics_partials', to: 'static#basics_partials', as: 'basics_partials'
  get 'ecosmarte_university', to: 'static#ecosmarte_university', as: 'ecosmarte_university'
  get 'ecosmarte_basics', to: 'static#ecosmarte_basics', as: 'ecosmarte_basics'
  get 'quiz/:quiz_number', to: 'static#quiz', as: 'quiz'
  post 'quiz_answer', to: 'static#quiz_answer', as: 'quiz_answer'
  get 'videos', to: 'static#videos', as: 'videos'
  
  get 'password_edit/:id', to: 'users#password_edit', as: 'password_edit'
  patch 'password_update/:id', to: 'users#password_update', as: 'password_update'
  
  get 'user_profile', to: 'users#user_profile', as: 'user_profile'
  get 'user_profile_edit', to: 'users#user_profile_edit', as: 'user_profile_edit'
  patch 'user_profile_update', to: 'users#user_profile_update', as: 'user_profile_update'
  get 'user_password_edit', to: 'users#user_password_edit', as: 'user_password_edit'
  patch 'user_password_update', to: 'users#user_password_update', as: 'user_password_update'
  
  get 'user_pools', to: 'pools#user_pools', as: 'user_pools'
  get 'add_pool', to: 'pools#add_pool', as: 'add_pool'
  get 'admin_edit_pool/:pool_id', to: 'pools#admin_edit_pool', as: 'admin_edit_pool'
  
  get 'new_water_measurement/:pool_id', to: 'waters#new_water_measurement', as: 'new_water_measurement'
  get 'user_water_measurements', to: 'waters#user_water_measurements', as: 'user_water_measurements'
  get 'pool_water_measurements/:pool_id', to: 'waters#pool_water_measurements', as: 'pool_water_measurements'
  
  get 'international', to: 'static#international', as: 'international'
  post 'international_mail', to: 'static#international_mail', as: 'international_mail'
  get 'ecosmarte__wifi', to: 'static#ecosmarte_wifi', as: 'ecosmarte_wifi'
  get 'privacy_policy', to: 'static#privacy_policy', as: 'privacy_policy'
  
end

app/models/water.rb
class Water < ApplicationRecord
  belongs_to :pool
  
  enum temperature_unit: %w(fahrenheit celcius)
  
  def self.get_all_pool_measurements(pool_id)
    Water.where(pool_id: pool_id).order(measurement_date: :desc)
  end
end

app/controllers/waters_controller.rb
class WatersController < ApplicationController
  include StrongParamsHolder
  
  before_action :authenticate_user!

  def index
    @pools = Pool.all
    @waters = Water.all.order(measurement_date: :desc)
  end

  def show
    @water = Water.find(params[:id])
  end

  def new
    @water = Water.new()
  end

  def create
    @water = Water.new(water_params)
    if @water.save
      if current_user.user_type == "admin"
        redirect_to waters_path
      else
        redirect_to user_water_measurements_path
      end
    else
      render :new
    end
  end

  def edit
    @water = Water.find(params[:id])
    @pool = Pool.find(@water.pool_id)
  end

  def update
    @water = Water.find(params[:id])
    if @water.update_attributes(water_params)
      if current_user.user_type == "admin"
        redirect_to waters_path
      else
        redirect_to user_water_measurements_path
      end
    else
      render :edit
    end
  end

  def destroy
    @water = Water.find(params[:id])
    @water.destroy
    if current_user.user_type == "admin"
      redirect_to waters_path
    else
      redirect_to user_water_measurements_path
    end
  end
  
  def new_water_measurement
    @pool = Pool.find(params[:pool_id])
    @water = Water.new()
    render :new
  end
  
  def user_water_measurements
    @pools = Pool.get_user_pools(current_user.id)
    @waters = Water.all
    render :index
  end
  
  def pool_water_measurements
    @pool = Pool.find(params[:pool_id])
    @waters = Water.get_all_pool_measurements(@pool.id)
    respond_to do |format|
      format.js {render layout: false} # Add this line to you respond_to block
    end
  end
end

app/helpers/waters_helper.rb
module WatersHelper
end

app/views/waters/_form.html.erb
<!-- Logo -->
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <%= image_tag 'ecosmarte.png', class: 'logo_eco' %>
  </div>
</div>
<!--  ------>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for @water, html: {class: 'form-horizontal'}, novalidate: 'novalidate' do |f| %>
    
      <div class="row">
        <div class="form-group group">
          <%= f.label :measurement_date, class: "col-sm-3 control-label" %>
          <div class="col-sm-8">
            <%= f.date_field :measurement_date, {class: "form-control date", required: "required", pattern: "[0-9]{2}[\/|-]{1}[0-9]{2}[\/|-]{1}[0-9]{4}$"} %>
          </div>
        </div>
      </div>
    
      <div class="row">
        <div class="form-group group">
          <%= f.label :temperature, class: "col-sm-3 control-label"%>
          <div class="col-sm-5">
            <%= f.text_field :temperature, class: "form-control", autofocus: true  %>
          </div>
          <div class="col-sm-3">
            <%= f.select :temperature_unit, options_for_select(Water.temperature_units.keys.map { |t| [t.humanize, t] }, @water.temperature_unit), {include_blank: "Choose"}, {class: "form-control"} %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :ph, "pH <small style='font-weight:normal;'><br>(6.8 - 7.2 Ideal)</small>".html_safe, class: "col-sm-3 control-label" %>
          <div class="col-sm-8">
            <%= f.text_field :ph, class: "form-control", autofocus: true %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :cuppm, "Cu (ppm) <small style='font-weight:normal;'><br>(0.4 - 0.7 Ideal)</small>".html_safe, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :cuppm, class: "form-control", autofocus: true %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :calcium, "Calcium <small style='font-weight:normal;'><br>(400+ Ideal)</small>".html_safe, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :calcium, class: "form-control", autofocus: true %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :phosphate, "Phosphate (ppb) <small style='font-weight:normal;'><br>(0 - 100 Ideal)</small>".html_safe, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :phosphate, class: "form-control", autofocus: true %>
          </div>
        </div>
      </div>
      
      <% if @pool.user.user_type == "commercial" %>
        <div class="row">
          <div class="form-group group">
            <%= f.label :free_chlorine, class: "col-sm-3 control-label"%>
            <div class="col-sm-8">
              <%= f.text_field :free_chlorine, class: "form-control", autofocus: true %>
            </div>
          </div>
        </div>
        
        <div class="row">
          <div class="form-group group">
            <%= f.label :total_chlorine, class: "col-sm-3 control-label"%>
            <div class="col-sm-8">
              <%= f.text_field :total_chlorine, class: "form-control", autofocus: true %>
            </div>
          </div>
        </div>
      <% end %>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :oxygen, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :oxygen, class: "form-control", autofocus: true %>
          </div>
        </div>
      </div>
      
      <%= f.hidden_field :pool_id, value: @pool.id %>
      
      <div class="row">
        <div class="actions">
          <%= f.submit "Save", class: "btn btn-tutorial" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/waters/_measurements.html.erb
<h1>Water Measurements</h1>

<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="table-responsive">
      <table class="table">
        <tbody>
          <tr>
            <th>Pool Name</th>
            <th>Date</th>
            <th>Temperature</th>
            <th>pH</th>
            <th>Cu (ppm)</th>
            <th>Calcium</th>
            <th>Phosphate</th>
            <% if @pool.user.user_type == 'commercial' %>
              <th>Free Chlorine</th>
              <th>Total Chlorine</th>
            <% end %>
            <th>Oxygen</th>
            <th>Actions</th>
          </tr>
          <% @waters.each do |water| %>
            <tr>
              <td><%= water.pool.name %></td>
              <td><%= water.measurement_date %></td>
              <td><%= water.temperature %>  <%= water.temperature_unit.humanize if water.temperature_unit.present?%></td>
              <% if (water.ph.present? && (water.ph > 7.2 || water.ph < 6.8)) %>
                <td class="warning_field"><%= water.ph %></td>
              <% else %>
                <td><%= water.ph %></td>
              <% end %>
              <% if (water.cuppm.present? && (water.cuppm > 0.7 || water.cuppm < 0.4)) %>
                <td class="warning_field"><%= water.cuppm %></td>
              <% else %>
                <td><%= water.cuppm %></td>
              <% end %>
              <% if (water.calcium.present? && (water.calcium < 400.0)) %>
                <td class="warning_field"><%= water.calcium %></td>
              <% else %>
                <td><%= water.calcium %></td>
              <% end %>
              <% if (water.phosphate.present? && (water.phosphate > 100)) %>
                <td class="warning_field"><%= water.phosphate %></td>
              <% else %>
                <td><%= water.phosphate %></td>
              <% end %>
              <% if @pool.user.user_type == 'commercial' %>
                <td><%= water.free_chlorine %></td>
                <td><%= water.total_chlorine %></td>
              <% end %>
              <td><%= water.oxygen %></td>
              <td>
                <%= link_to edit_water_path(water), class:"btn btn-primary btn-circle" do %>
                  <i class="fa fa-pencil"></i>
                <% end %>
                <%= link_to water_path(water), class:"btn btn-danger btn-circle", method:"delete" do %>
                 <i class="fa fa-trash-o"></i>
               <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<button class="btn btn-default" id="close" name="button">Close</button>

app/views/waters/edit.html.erb
<div class="container-fluid">
  <%= render "form" %>
</div>

app/views/waters/index.html.erb
<h1>Pools</h1>

<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="table-responsive">
      <table class="table">
        <tr>
          <th>Pool Name</th>
          <th>Costumer Name</th>
          <th>Model</th>
          <th>Actions</th>
        </tr>
        <% @pools.each do |pool| %>
          <tr>
            <td><%= pool.name %></td>
            <td><%= pool.user.name %></td>
            <td><%= pool.pool_model.description if pool.pool_model.present? %></td>

            <td>
              <%= link_to new_water_measurement_path(pool_id: pool.id), class:"btn btn-measurement btn-circle" do %>
               Add Data
              <% end %>
              <%= link_to pool_water_measurements_path(pool_id: pool.id), class:"btn btn-measurement btn-circle open", remote: true do %>
               View Data
              <% end %>
            </td>

          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

<div id="measurements_view"></div>

<!-- <div class="">
  <%= link_to new_water_path do %>
    <button class="btn btn-tutorial" name="button">Add New Data</button>
  <% end %>
</div>
 -->

app/views/waters/new.html.erb
<div class="container-fluid">
  <%= render "form" %>
</div>

app/views/waters/pool_water_measurements.js.erb
$("#measurements_view").html("<%= escape_javascript(render partial: 'measurements' ) %>");
$('html, body').animate({scrollTop: ($(document).height())}, 160);

$("#close").click(function() {
  // $('#measurements_view').css('display', 'none');
  $("#measurements_view").html("");
});

app/views/waters/show.html.erb
<section class="container-fluid">
  <h1><%= @water.pool.name %> Measurements on <%= @water.measurement_date %></h1>

  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <div class="table-responsive">
        <table class="table">
          <tbody>
            <tr>
              <th>Pool Name</th>
              <th>Costumer Name</th>
              <th>Temperature</th>
              <th>pH</th>
              <th>Cu (ppm)</th>
              <th>Calcium</th>
              <th>Phosphate</th>
              <% if @pool.user.user_type == 'commercial' %>
                <th>Free Chlorine</th>
                <th>Total Chlorine</th>
              <% end %>
              <th>Oxygen</th>
            </tr>
            <tr>
              <td><%= @water.pool.name %></td>
              <td><%= @water.pool.user.name %></td>
              <td><%= "#{@water.temperature}  #{@water.temperature_unit.humanize}" %></td>
              <td><%= @water.ph %></td>
              <td><%= @water.cuppm %></td>
              <td><%= @water.calcium %></td>
              <td><%= @water.phosphate %></td>
              <% if @pool.user.user_type == 'commercial' %>
                <td><%= @water.free_chlorine %></td>
                <td><%= @water.total_chlorine %></td>
              <% end %>
              <td><%= @water.oxygen %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  

  <%= link_to '<button class="btn btn-default" name="button">Edit</button>'.html_safe, edit_water_path(@water.id) %>


</section>