config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  
  resources :contacts, only: [:index, :create]
  resources :warranty, only: [:index, :create]
  resources :users, only: [:index, :edit, :update, :destroy, :show]
  resources :pools
  resources :waters

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#index'
  
  get 'startup_faq', to: 'static#startup_faq', as: 'startup_faq'
  get 'documents', to: 'static#documents', as: 'documents'
  get 'interactive_help', to: 'static#interactive_help', as: 'interactive_help'
  # get 'tutorial/:tutorial', to: 'static#tutorial', as: 'tutorial'
  get 'pool_tutorial', to: 'static#pool_tutorial', as: 'pool_tutorial'
  get 'spa_tutorial', to: 'static#spa_tutorial', as: 'spa_tutorial'
  get 'commercial_tutorial', to: 'static#commercial_tutorial', as: 'commercial_tutorial'
  get 'basics_partials', to: 'static#basics_partials', as: 'basics_partials'
  get 'ecosmarte_university', to: 'static#ecosmarte_university', as: 'ecosmarte_university'
  get 'ecosmarte_basics', to: 'static#ecosmarte_basics', as: 'ecosmarte_basics'
  get 'quiz/:quiz_number', to: 'static#quiz', as: 'quiz'
  post 'quiz_answer', to: 'static#quiz_answer', as: 'quiz_answer'
  get 'videos', to: 'static#videos', as: 'videos'
  
  get 'password_edit/:id', to: 'users#password_edit', as: 'password_edit'
  patch 'password_update/:id', to: 'users#password_update', as: 'password_update'
  
  get 'user_profile', to: 'users#user_profile', as: 'user_profile'
  get 'user_profile_edit', to: 'users#user_profile_edit', as: 'user_profile_edit'
  patch 'user_profile_update', to: 'users#user_profile_update', as: 'user_profile_update'
  get 'user_password_edit', to: 'users#user_password_edit', as: 'user_password_edit'
  patch 'user_password_update', to: 'users#user_password_update', as: 'user_password_update'
  
  get 'user_pools', to: 'pools#user_pools', as: 'user_pools'
  get 'add_pool', to: 'pools#add_pool', as: 'add_pool'
  get 'admin_edit_pool/:pool_id', to: 'pools#admin_edit_pool', as: 'admin_edit_pool'
  
  get 'new_water_measurement/:pool_id', to: 'waters#new_water_measurement', as: 'new_water_measurement'
  get 'user_water_measurements', to: 'waters#user_water_measurements', as: 'user_water_measurements'
  get 'pool_water_measurements/:pool_id', to: 'waters#pool_water_measurements', as: 'pool_water_measurements'
  
  get 'international', to: 'static#international', as: 'international'
  post 'international_mail', to: 'static#international_mail', as: 'international_mail'
  get 'ecosmarte__wifi', to: 'static#ecosmarte_wifi', as: 'ecosmarte_wifi'
  get 'privacy_policy', to: 'static#privacy_policy', as: 'privacy_policy'
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pools
         
  enum user_type: %w(admin user company commercial whole_house factory)
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include StrongParamsHolder
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include StrongParamsHolder
  
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @pools = Pool.get_user_pools(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end
  
  def password_edit
    @user = User.find(params[:id])
    render :password_edit
  end
  
  def password_update
    @user = User.find(params[:id])
    if @user == current_user
      if @user.update_attributes(user_params)
        bypass_sign_in(@user)
        redirect_to users_path
      else
        redirect_to password_edit_path
      end
    else
      if @user.update_attributes(user_params)
        redirect_to users_path
      else
        redirect_to password_edit_path
      end
    end
  end
  
  def user_profile
    @pools = Pool.get_user_pools(current_user.id)
    @user = User.find(current_user.id)
    render :show
  end
  
  def user_profile_edit
    @user = User.find(current_user.id)
    render :edit
  end
  
  def user_profile_update
    @user = User.find(current_user.id)
    if @user.update_attributes(user_params)
      bypass_sign_in(@user)
      redirect_to user_profile_path
    else
      redirect_to user_profile_edit_path
    end
  end
  
  def user_password_edit
    @user = User.find(current_user.id)
    render :user_password_edit
  end
  
  def user_password_update
    @user = User.find(current_user.id)
    if @user.update_attributes(user_params)
      bypass_sign_in(@user)
      redirect_to user_profile_path
    else
      redirect_to user_password_edit_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<!-- Logo -->
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <%= image_tag 'ecosmarte.png', class: 'logo_eco' %>
  </div>
</div>
<!--  ------>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for @user, html: {class: 'form-horizontal'}, novalidate: 'novalidate' do |f| %>
      
      <% if @user.user_type != "admin" %>
      <div class="row">
        <div class="form-group group">
          <%= f.label :user_type, class: "col-sm-3 control-label" %>
          <div class="col-sm-8">
            <%#= f.select :user_type, User.user_types.keys.map { |t| [t.humanize, t] }, {}, {class: "form-control"} %>
            <%= f.select :user_type, user_type_array, {}, {class: "form-control", required: "required"} %>
          </div>
        </div>
      </div>
      <% end %>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :name, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :name, class: "form-control", required: "required", autofocus: true  %>
          </div>
        </div>
      </div>
      
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :email, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.email_field :email, class: "form-control", required: "required", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :phone, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :phone, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :address, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :address, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :city, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :city, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :postal_code, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :postal_code, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= link_to '<button class="btn btn-tutorial" name="button">Change Password</button>'.html_safe, password_edit_path(id: @user.id) %>
        </div>
      </div>
      
      <div class="row">
        <div class="actions">
          <%= f.submit "Save", class: "btn btn-tutorial" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/users/_form_profile.html.erb
<!-- Logo -->
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <%= image_tag 'ecosmarte.png', class: 'logo_eco' %>
  </div>
</div>
<!--  ------>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for @user, url: {action: :user_profile_update}, html: {class: 'form-horizontal'}, novalidate: 'novalidate' do |f| %>
      
      <% if @user.user_type != "admin" %>
      <div class="row">
        <div class="form-group group">
          <%= f.label :user_type, class: "col-sm-3 control-label" %>
          <div class="col-sm-8">
            <%#= f.select :user_type, User.user_types.keys.map { |t| [t.humanize, t] }, {}, {class: "form-control"} %>
            <%= f.select :user_type, user_type_array, {}, {class: "form-control", required: "required"} %>
          </div>
        </div>
      </div>
      <% end %>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :name, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :name, class: "form-control", required: "required", autofocus: true  %>
          </div>
        </div>
      </div>
      
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :email, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.email_field :email, class: "form-control", required: "required", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :phone, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :phone, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :address, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :address, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :city, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :city, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :postal_code, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :postal_code, class: "form-control", autofocus: true  %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= link_to '<button class="btn btn-tutorial" name="button">Change Password</button>'.html_safe, user_password_edit_path %>
        </div>
      </div>
      
      <div class="row">
        <div class="actions">
          <%= f.submit "Save", class: "btn btn-tutorial" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container-fluid">
  <% if current_user.user_type == "admin" %>
    <%= render "form" %>
  <% else %>
    <%= render "form_profile" %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="table-responsive">
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>User type</th>
          <th>Actions</th>
        </tr>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= role(user.user_type) %></td>

            <td>
              <%= link_to user_path(user), class:"btn btn-success btn-circle" do %>
                <i class="fa fa-eye"></i>
              <% end %>
              <%= link_to edit_user_path(user), class:"btn btn-primary btn-circle" do %>
                <i class="fa fa-pencil"></i>
              <% end %>
              <%= link_to user_path(user), class:"btn btn-danger btn-circle", method:"delete" do %>
               <i class="fa fa-trash-o"></i>
             <% end %>
            </td>

          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container-fluid">
  <%= render "form" %>
</div>

app/views/users/password_edit.html.erb
<!-- Logo -->
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <%= image_tag 'ecosmarte.png', class: 'logo_eco' %>
  </div>
</div>
<!--  ------>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for @user, url: {action: :password_update}, html: {class: 'form-horizontal'}, novalidate: 'novalidate' do |f| %>

      <div class="row">
        <div class="form-group group">
          <%= f.label :new_password, class: "col-sm-3 control-label"%>
          <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %>
          <div class="col-sm-8">
            <%= f.password_field :password, class: "form-control", required: "required", autocomplete: "off" %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :password_confirmation, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.password_field :password_confirmation, class: "form-control", required: "required", autocomplete: "off" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="actions">
          <%= f.submit "Save", class: "btn btn-tutorial" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<section class="container-fluid">
  <h1><%= @user.name %></h1>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="table-responsive">
        <table class="table">
          <tbody>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>User Type</th>
              <th>Phone</th>
              <th>Address</th>
              <th>City</th>
              <th>Postal Code</th>
            </tr>
            <tr>
              <td><%= @user.name %></td>
              <td><%= @user.email %></td>
              <td><%= role(@user.user_type) %></td>
              <td><%= @user.phone %></td>
              <td><%= @user.address %></td>
              <td><%= @user.city %></td>
              <td><%= @user.postal_code %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  
  <% if current_user.user_type == "admin" %>
    <%= link_to '<button class="btn btn-default" name="button">Edit</button>'.html_safe, edit_user_path(@user.id) %>
  <% else %>
    <%= link_to '<button class="btn btn-default" name="button">Edit</button>'.html_safe, user_profile_edit_path %>
  <% end %>
  
  <% if current_user.user_type == "admin" %>
    <div class="row">
      <h3>Costumer's pools</h3>
      <div class="col-sm-8 col-sm-offset-2">
        <div class="table-responsive">
          <table class="table">
            <tr>
              <th>Pool Name</th>
              <th>Costumer Name</th>
              <th>Model</th>
              <th>Actions</th>
            </tr>
            <% if @pools.present? %>
              <% @pools.each do |pool| %>
                <tr>
                  <td><%= pool.name %></td>
                  <td><%= pool.user.name %></td>
                  <td><%= pool.pool_model.description if pool.pool_model.present? %></td>

                  <td>
                    <%= link_to pool_path(pool), class:"btn btn-success btn-circle" do %>
                      <i class="fa fa-eye"></i>
                    <% end %>
                    <% if current_user.user_type == "admin" %>
                      <%= link_to admin_edit_pool_path(pool), class:"btn btn-primary btn-circle" do %>
                        <i class="fa fa-pencil"></i>
                      <% end %>
                    <% else %>
                      <%= link_to edit_pool_path(pool), class:"btn btn-primary btn-circle" do %>
                        <i class="fa fa-pencil"></i>
                      <% end %>
                    <% end %>
                    <%= link_to pool_path(pool), class:"btn btn-danger btn-circle", method:"delete" do %>
                     <i class="fa fa-trash-o"></i>
                   <% end %>
                  </td>

                </tr>
              <% end %>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  <% end %>

</section>

app/views/users/user_password_edit.html.erb
<!-- Logo -->
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <%= image_tag 'ecosmarte.png', class: 'logo_eco' %>
  </div>
</div>
<!--  ------>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for @user, url: {action: :user_password_update}, html: {class: 'form-horizontal'}, novalidate: 'novalidate' do |f| %>

      <div class="row">
        <div class="form-group group">
          <%= f.label :new_password, class: "col-sm-3 control-label"%>
          <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %>
          <div class="col-sm-8">
            <%= f.password_field :password, class: "form-control", required: "required", autocomplete: "off" %>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="form-group group">
          <%= f.label :password_confirmation, class: "col-sm-3 control-label"%>
          <div class="col-sm-8">
            <%= f.password_field :password_confirmation, class: "form-control", required: "required", autocomplete: "off" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="actions">
          <%= f.submit "Save", class: "btn btn-tutorial" %>
        </div>
      </div>

    <% end %>
  </div>
</div>