config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  
  resources :contacts, only: [:index, :create]
  resources :warranty, only: [:index, :create]
  resources :users, only: [:index, :edit, :update, :destroy, :show]
  resources :pools
  resources :waters

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#index'
  
  get 'startup_faq', to: 'static#startup_faq', as: 'startup_faq'
  get 'documents', to: 'static#documents', as: 'documents'
  get 'interactive_help', to: 'static#interactive_help', as: 'interactive_help'
  # get 'tutorial/:tutorial', to: 'static#tutorial', as: 'tutorial'
  get 'pool_tutorial', to: 'static#pool_tutorial', as: 'pool_tutorial'
  get 'spa_tutorial', to: 'static#spa_tutorial', as: 'spa_tutorial'
  get 'commercial_tutorial', to: 'static#commercial_tutorial', as: 'commercial_tutorial'
  get 'basics_partials', to: 'static#basics_partials', as: 'basics_partials'
  get 'ecosmarte_university', to: 'static#ecosmarte_university', as: 'ecosmarte_university'
  get 'ecosmarte_basics', to: 'static#ecosmarte_basics', as: 'ecosmarte_basics'
  get 'quiz/:quiz_number', to: 'static#quiz', as: 'quiz'
  post 'quiz_answer', to: 'static#quiz_answer', as: 'quiz_answer'
  get 'videos', to: 'static#videos', as: 'videos'
  
  get 'password_edit/:id', to: 'users#password_edit', as: 'password_edit'
  patch 'password_update/:id', to: 'users#password_update', as: 'password_update'
  
  get 'user_profile', to: 'users#user_profile', as: 'user_profile'
  get 'user_profile_edit', to: 'users#user_profile_edit', as: 'user_profile_edit'
  patch 'user_profile_update', to: 'users#user_profile_update', as: 'user_profile_update'
  get 'user_password_edit', to: 'users#user_password_edit', as: 'user_password_edit'
  patch 'user_password_update', to: 'users#user_password_update', as: 'user_password_update'
  
  get 'user_pools', to: 'pools#user_pools', as: 'user_pools'
  get 'add_pool', to: 'pools#add_pool', as: 'add_pool'
  get 'admin_edit_pool/:pool_id', to: 'pools#admin_edit_pool', as: 'admin_edit_pool'
  
  get 'new_water_measurement/:pool_id', to: 'waters#new_water_measurement', as: 'new_water_measurement'
  get 'user_water_measurements', to: 'waters#user_water_measurements', as: 'user_water_measurements'
  get 'pool_water_measurements/:pool_id', to: 'waters#pool_water_measurements', as: 'pool_water_measurements'
  
  get 'international', to: 'static#international', as: 'international'
  post 'international_mail', to: 'static#international_mail', as: 'international_mail'
  get 'ecosmarte__wifi', to: 'static#ecosmarte_wifi', as: 'ecosmarte_wifi'
  get 'privacy_policy', to: 'static#privacy_policy', as: 'privacy_policy'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecosmarte Cloud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'brand_2.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  </head>

  <body>
    <div id="wrap">
      <!-- <nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="158" role="navigation"> -->
      <nav class="navbar navbar-default navbar-fixed-top affix" role="navigation">
          <div class="container-fluid">
            <div class="navbar-header">
              <%= link_to root_path, class: "navbar-brand" do %>
                <%= image_tag "brand.png", class: "brand_logo" %>
              <% end %>
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div class="navbar-collapse collapse">
              <% if current_user %>
                <ul class="nav navbar-nav">
                  <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to 'Home', root_path %></li>
                  <li class="<%= 'active' if (current_page?(interactive_help_path) || current_page?(pool_tutorial_path)  || current_page?(spa_tutorial_path)  || current_page?(commercial_tutorial_path)) %>">
                    <%= link_to 'Interactive Help', interactive_help_path %>
                  </li>
                  <li class="<%= 'active' if current_page?(ecosmarte_university_path) %>"><%= link_to 'Ecosmarte University', ecosmarte_university_path %></li>
                  <li class="<%= 'active' if current_page?(documents_path) %>"><%= link_to 'Documents', documents_path %></li>
                  <li class="<%= 'active' if current_page?(startup_faq_path) %>"><%= link_to 'Start up/FAQ', startup_faq_path %></li>
                  <li class="<%= 'active' if current_page?(contacts_path) %>"><%= link_to 'Contact Us', contacts_path %></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li class="dropdown">
                      <%= link_to root_path, {class: "dropdown-toggle", "data-toggle" => "dropdown", role: "button"} do %>
                      Hello, <%= current_user.name %> <span class="caret"></span>
                      <% end %>
                		<ul class="dropdown-menu">
                  		<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
                  		<!--  It does not exist on non admins -->
                		</ul>
              		</li>
                </ul>
              <% else %>
                <ul class="nav navbar-nav">
                  <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to 'Home', root_path %></li>
                  <li class="<%= 'active' if current_page?(startup_faq_path)  %>"><%= link_to 'Start up/FAQ', startup_faq_path %></li>
                  <li class="<%= 'active' if current_page?(contacts_path) %>"><%= link_to 'Contact Us', contacts_path %></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li>
                    <%= link_to "Register", new_user_registration_path  %>
                  </li>
                  <li>
                    <%= link_to "Login",  new_user_session_path  %>
                  </li>
                </ul>
              <% end %>
            </div><!--/.nav-collapse -->
          </div>
      </nav>
    
      <section id="content" class="container-fluid">
        <%= yield %>
      </section>
    </div>
    
    <footer>
      <div class="col-sm-10 col-sm-offset-1">
        <div class="row">
          <div class="col-sm-4">
            <div class="social_icons">
              <div class="social_icon">
                <%= link_to "https://www.facebook.com/ECOsmartePlanetFriendlyUSA/", target: "_blank" do %>
                  <%= image_tag "fb_icon.png" %>
                <% end %>
      			  </div>
              <div class="social_icon">
                <%= link_to "https://twitter.com/Ecosmarte2", target: "_blank" do %>
                  <%= image_tag "twitter_icon.png" %>
                <% end %>
      			  </div>
              <div class="social_icon">
                <%= link_to "https://www.linkedin.com/company-beta/3695970/", target: "_blank" do %>
                  <%= image_tag "linkedin_icon.png" %>
                <% end %>
      			  </div>
            </div>
          </div>
          
          <div class="col-sm-4 col-sm-offset-4" id="footer_help_links">
            <div class="footer_link"><%= link_to "Submit Warranty", warranty_index_path %></div>
            <div class="footer_link"><%= link_to "Order Products", "http://www.ecosmarteonlinestore.com/", target: "_blank" %></div>
            <div class="footer_link"><%= link_to "Privacy Policy", privacy_policy_path %></div>
          </div>
        </div>
        
        <div class="row" id="rights">
          Copyright ECOsmarte Cloud. All Rights Reserved.  
        </div>
      </div>
    </footer>
    
  </body>
</html>